/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fee_management_system;

import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author souls
 */
public class PrintReciept extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrintReciept.class.getName());

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        getRecords();
        Container c = getContentPane();
        c.setBackground(new Color(0,153,153));
    }
    
    public void getRecords()
    {
        try {
            Connection con = DBConnection.getconnection();
            PreparedStatement pst = con.prepareStatement("select * from fees_details order by reciept_no desc fetch first 1 rows only");
            ResultSet rs = pst.executeQuery();
            rs.next();
            
            txt_receiptNo.setText(rs.getString("reciept_no"));
            txt_paymentMode.setText(rs.getString("payment_mode"));
            
            String paymentMode = rs.getString("payment_mode");
            
            if (paymentMode.equalsIgnoreCase("cash")) {
                lbl_cheque_dd.setText("Cheque No ");
                txt_cheque_dd.setText("-");
                txt_bankName.setText("-");
            }
            
            if (paymentMode.equalsIgnoreCase("cheque")) {
                lbl_cheque_dd.setText("Cheque No ");
                txt_cheque_dd.setText(rs.getString("cheque_no"));
                txt_bankName.setText(rs.getString("bank_name"));
            }
            
            if (paymentMode.equalsIgnoreCase("dd")) {
                lbl_cheque_dd.setText("DD No ");
                txt_cheque_dd.setText(rs.getString("dd_no"));
                txt_bankName.setText(rs.getString("bank_name"));
            }
            
            if (paymentMode.equalsIgnoreCase("card")) {
                lbl_cheque_dd.setText("Cheque No ");
                txt_cheque_dd.setText(rs.getString("-"));
                txt_bankName.setText(rs.getString("bank_name"));
            }
            
            txt_recievedFrom.setText(rs.getString("student_name"));
            txt_date.setText(rs.getString("date"));
            txt_gstin.setText(rs.getString("gstin"));
            txt_year1.setText(rs.getString("year1"));
            txt_year2.setText(rs.getString("year2"));
            
            txt_initialamount.setText(rs.getString("amount"));
            txt_cgst.setText(rs.getString("cgst"));
            txt_sgst.setText(rs.getString("sgst"));
            txt_total.setText(rs.getString("total_amount"));
            txt_totalInWords.setText(rs.getString("total_in_words"));
            txt_remark.setText(rs.getString("remark"));
            txt_courseName.setText(rs.getString("course_name"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        btn_edit7 = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        btnSearch = new javax.swing.JLabel();
        btn_edit4 = new javax.swing.JLabel();
        panelEdit = new javax.swing.JPanel();
        btnEdit = new javax.swing.JLabel();
        btn_edit6 = new javax.swing.JLabel();
        panelCourseList = new javax.swing.JPanel();
        btnCourseList = new javax.swing.JLabel();
        btn_edit5 = new javax.swing.JLabel();
        panelViewAllRecord = new javax.swing.JPanel();
        btnViewAllRecord = new javax.swing.JLabel();
        btn_edit9 = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        btn_edit8 = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        btn_edit = new javax.swing.JLabel();
        panelprint = new javax.swing.JPanel();
        btn_print = new javax.swing.JLabel();
        btn_edit3 = new javax.swing.JLabel();
        panelHome1 = new javax.swing.JPanel();
        btn_edit1 = new javax.swing.JLabel();
        btn_edit2 = new javax.swing.JLabel();
        panel_print = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_receiptNo = new javax.swing.JLabel();
        txt_paymentMode = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_cheque_dd = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        txt_bankName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_recievedFrom = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        lbl_bankName = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_totalInWords = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_courseName = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        cgst = new javax.swing.JLabel();
        txt_initialamount = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_sgst = new javax.swing.JLabel();
        sgst = new javax.swing.JLabel();
        sgst2 = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        sgst4 = new javax.swing.JLabel();
        sgst5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelHomeMouseExited(evt);
            }
        });
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        panelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 130, 40));

        btn_edit7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_edit7.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management_system/images/home.png"))); // NOI18N
        btn_edit7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit7MouseExited(evt);
            }
        });
        panelHome.add(btn_edit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 70));

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 440, -1));

        panelSearch.setBackground(new java.awt.Color(0, 102, 102));
        panelSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSearchMouseExited(evt);
            }
        });
        panelSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search Record");
        panelSearch.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 250, 40));

        btn_edit4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_edit4.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management_system/images/search2.png"))); // NOI18N
        btn_edit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit4MouseExited(evt);
            }
        });
        panelSearch.add(btn_edit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 70));

        panelsideBar.add(panelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 440, 70));

        panelEdit.setBackground(new java.awt.Color(0, 102, 102));
        panelEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEditMouseExited(evt);
            }
        });
        panelEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit Course");
        panelEdit.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 220, 40));

        btn_edit6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_edit6.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management_system/images/edit2.png"))); // NOI18N
        btn_edit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit6MouseExited(evt);
            }
        });
        panelEdit.add(btn_edit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 70));

        panelsideBar.add(panelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 440, 70));

        panelCourseList.setBackground(new java.awt.Color(0, 102, 102));
        panelCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCourseListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCourseListMouseExited(evt);
            }
        });
        panelCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourseList.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnCourseList.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList.setText("Course List");
        panelCourseList.add(btnCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 210, 40));

        btn_edit5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_edit5.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management_system/images/list_1.png"))); // NOI18N
        btn_edit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit5MouseExited(evt);
            }
        });
        panelCourseList.add(btn_edit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 70));

        panelsideBar.add(panelCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 440, 70));

        panelViewAllRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelViewAllRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelViewAllRecordMouseExited(evt);
            }
        });
        panelViewAllRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAllRecord.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecord.setText("View All Records");
        panelViewAllRecord.add(btnViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 300, 50));

        btn_edit9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_edit9.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management_system/images/view all record.png"))); // NOI18N
        btn_edit9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit9MouseExited(evt);
            }
        });
        panelViewAllRecord.add(btn_edit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 70));

        panelsideBar.add(panelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 440, 70));

        panelBack.setBackground(new java.awt.Color(0, 102, 102));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBackMouseExited(evt);
            }
        });
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        panelBack.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 130, 50));

        btn_edit8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_edit8.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management_system/images/left-arrow.png"))); // NOI18N
        btn_edit8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit8MouseExited(evt);
            }
        });
        panelBack.add(btn_edit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 70));

        panelsideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 440, 70));

        panelLogout.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLogoutMouseExited(evt);
            }
        });
        panelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        panelLogout.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 50));

        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management_system/images/logout.png"))); // NOI18N
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        panelLogout.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 70));

        panelsideBar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 440, -1));

        panelprint.setBackground(new java.awt.Color(0, 102, 102));
        panelprint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelprintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelprintMouseExited(evt);
            }
        });
        panelprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_print.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setText("Print");
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_printMouseExited(evt);
            }
        });
        panelprint.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 200, 70));

        btn_edit3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_edit3.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management_system/images/printer-.png"))); // NOI18N
        btn_edit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit3MouseExited(evt);
            }
        });
        panelprint.add(btn_edit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 70));

        panelsideBar.add(panelprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 440, 70));

        panelHome1.setBackground(new java.awt.Color(0, 102, 102));
        panelHome1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHome1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelHome1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelHome1MouseExited(evt);
            }
        });
        panelHome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_edit1.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit1.setText("Edit\n");
        btn_edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit1MouseExited(evt);
            }
        });
        panelHome1.add(btn_edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 80, 70));

        btn_edit2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_edit2.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fee_management_system/images/edit2.png"))); // NOI18N
        btn_edit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit2MouseExited(evt);
            }
        });
        panelHome1.add(btn_edit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 110, 70));

        panelsideBar.add(panelHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 710, 440, 70));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 850));

        panel_print.setBackground(new java.awt.Color(255, 255, 255));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("School of Computer Science");
        panel_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 250, -1));

        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("Old nagardas road,dr.radhakrishna marg,andheri west,mumbai 40063");
        panel_print.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 380, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("Bhartiya Vidhya Bhavans");
        panel_print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 210, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 102));
        jLabel4.setText("Since 1984");
        panel_print.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 180, -1));

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panel_print.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 670, 10));

        txt_receiptNo.setForeground(new java.awt.Color(51, 0, 102));
        txt_receiptNo.setText("Receipt No : ");
        panel_print.add(txt_receiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, -1));

        txt_paymentMode.setForeground(new java.awt.Color(51, 0, 102));
        txt_paymentMode.setText("Payment Mode : ");
        panel_print.add(txt_paymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, -1));

        jLabel7.setForeground(new java.awt.Color(51, 0, 102));
        jLabel7.setText("Receipt No :     SOC-");
        panel_print.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        txt_cheque_dd.setForeground(new java.awt.Color(51, 0, 102));
        txt_cheque_dd.setText("cheque_dd :");
        panel_print.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 120, -1));

        jLabel9.setForeground(new java.awt.Color(51, 0, 102));
        jLabel9.setText("Payment Mode : ");
        panel_print.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, -1));

        jLabel10.setForeground(new java.awt.Color(51, 0, 102));
        jLabel10.setText("The following payment in the college for the year");
        panel_print.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 270, -1));

        lbl_cheque_dd.setForeground(new java.awt.Color(51, 0, 102));
        lbl_cheque_dd.setText("cheque_dd :");
        panel_print.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, -1));

        txt_bankName.setForeground(new java.awt.Color(51, 0, 102));
        txt_bankName.setText("Bank Name :");
        panel_print.add(txt_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 120, -1));

        jLabel13.setForeground(new java.awt.Color(51, 0, 102));
        jLabel13.setText("-");
        panel_print.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 20, -1));

        txt_recievedFrom.setForeground(new java.awt.Color(51, 0, 102));
        txt_recievedFrom.setText("Recieved From :");
        panel_print.add(txt_recievedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 120, -1));

        txt_year1.setForeground(new java.awt.Color(51, 0, 102));
        txt_year1.setText("2021");
        panel_print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 30, -1));

        txt_year2.setForeground(new java.awt.Color(51, 0, 102));
        txt_year2.setText("2021");
        panel_print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 30, -1));

        lbl_bankName.setForeground(new java.awt.Color(51, 0, 102));
        lbl_bankName.setText("Bank Name :");
        panel_print.add(lbl_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, -1));

        txt_gstin.setForeground(new java.awt.Color(51, 0, 102));
        txt_gstin.setText("GSTIN :");
        panel_print.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 80, -1));

        jLabel19.setForeground(new java.awt.Color(51, 0, 102));
        jLabel19.setText("Amount(Rs)");
        panel_print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 70, 20));

        txt_date.setForeground(new java.awt.Color(51, 0, 102));
        txt_date.setText("Date :");
        panel_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 80, -1));

        jLabel21.setForeground(new java.awt.Color(51, 0, 102));
        jLabel21.setText("Date :");
        panel_print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 50, -1));

        jLabel22.setForeground(new java.awt.Color(51, 0, 102));
        jLabel22.setText("GSTIN :");
        panel_print.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 50, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 140, 10));

        jSeparator2.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 670, 20));

        txt_totalInWords.setForeground(new java.awt.Color(51, 0, 102));
        txt_totalInWords.setText("Total in Words :");
        panel_print.add(txt_totalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 250, -1));

        jLabel23.setForeground(new java.awt.Color(51, 0, 102));
        jLabel23.setText("Sr No");
        panel_print.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 40, 20));

        jLabel24.setForeground(new java.awt.Color(51, 0, 102));
        jLabel24.setText("Head");
        panel_print.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 40, 20));

        jLabel25.setForeground(new java.awt.Color(51, 0, 102));
        jLabel25.setText("Recieved From :");
        panel_print.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, -1));

        jLabel26.setForeground(new java.awt.Color(51, 0, 102));
        jLabel26.setText("1");
        panel_print.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 120, -1));

        txt_courseName.setForeground(new java.awt.Color(51, 0, 102));
        txt_courseName.setText("1");
        panel_print.add(txt_courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 120, -1));

        txt_total.setForeground(new java.awt.Color(51, 0, 102));
        txt_total.setText("total");
        panel_print.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 120, -1));

        cgst.setForeground(new java.awt.Color(51, 0, 102));
        cgst.setText("cgst(9 %)");
        panel_print.add(cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 120, -1));

        txt_initialamount.setForeground(new java.awt.Color(51, 0, 102));
        txt_initialamount.setText("cgst");
        panel_print.add(txt_initialamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 120, -1));

        txt_cgst.setForeground(new java.awt.Color(51, 0, 102));
        txt_cgst.setText("cgst");
        panel_print.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 120, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 670, 20));

        txt_sgst.setForeground(new java.awt.Color(51, 0, 102));
        txt_sgst.setText("cgst");
        panel_print.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 120, -1));

        sgst.setForeground(new java.awt.Color(51, 0, 102));
        sgst.setText("sgst(9 %)");
        panel_print.add(sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 120, -1));

        sgst2.setForeground(new java.awt.Color(51, 0, 102));
        sgst2.setText("Reciever Signature ");
        panel_print.add(sgst2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 120, -1));

        txt_remark.setForeground(new java.awt.Color(51, 0, 102));
        txt_remark.setText("Remark :");
        panel_print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 120, -1));

        jSeparator4.setForeground(new java.awt.Color(51, 0, 102));
        panel_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 120, 20));

        sgst4.setForeground(new java.awt.Color(51, 0, 102));
        sgst4.setText("Total in Words :");
        panel_print.add(sgst4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, -1));

        sgst5.setForeground(new java.awt.Color(51, 0, 102));
        sgst5.setText("Remark :");
        panel_print.add(sgst5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 120, -1));

        getContentPane().add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 670, 620));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Print Receipt");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 330, 80));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 420, 10));

        setSize(new java.awt.Dimension(1602, 858));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseEntered
        Color clr= new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_panelHomeMouseEntered

    private void panelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseExited
        Color clr= new Color(0,103,103);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_panelHomeMouseExited

    private void panelSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchMouseEntered
        Color clr= new Color(0,153,153);
        panelSearch.setBackground(clr);
    }//GEN-LAST:event_panelSearchMouseEntered

    private void panelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchMouseExited
        Color clr= new Color(0,103,103);
        panelSearch.setBackground(clr);
    }//GEN-LAST:event_panelSearchMouseExited

    private void panelEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditMouseEntered
        Color clr= new Color(0,153,153);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_panelEditMouseEntered

    private void panelEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditMouseExited
        Color clr= new Color(0,103,103);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_panelEditMouseExited

    private void panelCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCourseListMouseEntered
        Color clr= new Color(0,153,153);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_panelCourseListMouseEntered

    private void panelCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCourseListMouseExited
        Color clr= new Color(0,103,103);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_panelCourseListMouseExited

    private void panelViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewAllRecordMouseEntered
        Color clr= new Color(0,153,153);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_panelViewAllRecordMouseEntered

    private void panelViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewAllRecordMouseExited
        Color clr= new Color(0,103,103);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_panelViewAllRecordMouseExited

    private void panelBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBackMouseEntered
        Color clr= new Color(0,153,153);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_panelBackMouseEntered

    private void panelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBackMouseExited
        Color clr= new Color(0,103,103);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_panelBackMouseExited

    private void panelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseEntered
        Color clr= new Color(0,153,153);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_panelLogoutMouseEntered

    private void panelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseExited
        Color clr= new Color(0,103,103);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_panelLogoutMouseExited

    private void panelprintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelprintMouseEntered
        Color clr= new Color(0,153,153);
        panelprint.setBackground(clr);
    }//GEN-LAST:event_panelprintMouseEntered

    private void panelprintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelprintMouseExited
        Color clr= new Color(0,103,103);
        panelprint.setBackground(clr);
    }//GEN-LAST:event_panelprintMouseExited

    private void panelHome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHome1MouseEntered
        Color clr= new Color(0,153,153);
        panelHome1.setBackground(clr);
    }//GEN-LAST:event_panelHome1MouseEntered

    private void panelHome1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHome1MouseExited
       Color clr= new Color(0,103,103);
        panelHome1.setBackground(clr);
    }//GEN-LAST:event_panelHome1MouseExited

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_btn_printMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        UpdateFeesDetails update = new UpdateFeesDetails();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseEntered
        Color clr= new Color(0,153,153);
        btn_print.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseEntered

    private void btn_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseExited
        Color clr= new Color(0,103,103);
        btn_print.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseExited

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
        Color clr= new Color(0,153,153);
        btn_edit.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        Color clr= new Color(0,103,103);
        btn_edit.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_edit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit1MouseClicked
        
    }//GEN-LAST:event_btn_edit1MouseClicked

    private void btn_edit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit1MouseEntered

    private void btn_edit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit1MouseExited

    private void btn_edit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit2MouseClicked

    private void btn_edit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit2MouseEntered

    private void btn_edit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit2MouseExited

    private void btn_edit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit3MouseClicked

    private void btn_edit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit3MouseEntered

    private void btn_edit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit3MouseExited

    private void btn_edit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit4MouseClicked

    private void btn_edit4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit4MouseEntered

    private void btn_edit4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit4MouseExited

    private void btn_edit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit5MouseClicked

    private void btn_edit5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit5MouseEntered

    private void btn_edit5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit5MouseExited

    private void btn_edit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit6MouseClicked

    private void btn_edit6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit6MouseEntered

    private void btn_edit6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit6MouseExited

    private void btn_edit7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit7MouseClicked

    private void btn_edit7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit7MouseEntered

    private void btn_edit7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit7MouseExited

    private void btn_edit8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit8MouseClicked

    private void btn_edit8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit8MouseEntered

    private void btn_edit8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit8MouseExited

    private void btn_edit9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit9MouseClicked

    private void btn_edit9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit9MouseEntered

    private void btn_edit9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit9MouseExited

    private void panelHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHome1MouseClicked
        UpdateFeesDetails update = new UpdateFeesDetails();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelHome1MouseClicked

    private void panelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseClicked
        home home = new home();
        home.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_panelHomeMouseClicked

    private void panelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchMouseClicked
        SearchRecord search = new SearchRecord();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelSearchMouseClicked

    private void panelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditMouseClicked
        EditCourse course = new EditCourse();
        course.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelEditMouseClicked

    private void panelCourseListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCourseListMouseClicked
        EditCourse edit = new EditCourse();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelCourseListMouseClicked

    private void panelViewAllRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewAllRecordMouseClicked
        ViewAllRecords record = new ViewAllRecords();
        record.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelViewAllRecordMouseClicked

    private void panelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBackMouseClicked
        AddFees add = new AddFees();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelBackMouseClicked

    private void panelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_panelLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrintReciept().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnCourseList;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnViewAllRecord;
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_edit1;
    private javax.swing.JLabel btn_edit2;
    private javax.swing.JLabel btn_edit3;
    private javax.swing.JLabel btn_edit4;
    private javax.swing.JLabel btn_edit5;
    private javax.swing.JLabel btn_edit6;
    private javax.swing.JLabel btn_edit7;
    private javax.swing.JLabel btn_edit8;
    private javax.swing.JLabel btn_edit9;
    private javax.swing.JLabel btn_print;
    private javax.swing.JLabel cgst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_bankName;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelCourseList;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelHome1;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelViewAllRecord;
    private javax.swing.JPanel panel_print;
    private javax.swing.JPanel panelprint;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JLabel sgst;
    private javax.swing.JLabel sgst2;
    private javax.swing.JLabel sgst4;
    private javax.swing.JLabel sgst5;
    private javax.swing.JLabel txt_bankName;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_courseName;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_initialamount;
    private javax.swing.JLabel txt_paymentMode;
    private javax.swing.JLabel txt_receiptNo;
    private javax.swing.JLabel txt_recievedFrom;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_totalInWords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
